apiVersion: v1
kind: ConfigMap
metadata:
  name: envconsul
data:
  config.hcl: |
    vault {
      address     = "http://ip:8200"
      token       = "hvs.token"
      renew_token = false
      ssl {
        enabled = false
        verify  = false
      }
    }
    secret {
      path = "secret/sinatra"
      format = "{{key}}"
      no_prefix = true
    }
