apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: envconsul
        image: hashicorp/envconsul
        command: ["cp", "/bin/envconsul", "/share/"]
        imagePullPolicy: Always
        volumeMounts:
        - name: envconsul-share
          mountPath: /share/
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.24
        command: ["/envconsul/envconsul", "-config", "/envconsul/config/config.hcl", "nginx", "-g", "daemon off;"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: envconsul-share
          mountPath: /envconsul/
        - name: envconsul-config
          mountPath: /envconsul/config/config.hcl
          subPath: config.hcl
      volumes:
      - name: envconsul-share
        emptyDir:
          medium: Memory
      - name: envconsul-config
        configMap:
          name: envconsul
