apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-deployment
  labels:
    app: sinatra
spec:
  replicas: 6
  selector:
    matchLabels:
      app: sinatra
  template:
    metadata:
      labels:
        app: sinatra
    spec:
      initContainers:
      - name: envconsul
        image: hashicorp/envconsul
        command: ["cp", "/bin/envconsul", "/share/"]
        imagePullPolicy: Always
        volumeMounts:
        - name: envconsul-share
          mountPath: /share/
      containers:
      - name: sinatra
        image: ecliptik/sinatra
        command: ["/envconsul/envconsul", "-config", "/envconsul/config/config.hcl", "bundle", "exec", "rackup", "-o", "0.0.0.0"]
        envFrom:
          - secretRef:
              name: sinatra
        ports:
        - containerPort: 9292
        volumeMounts:
        - name: envconsul-share
          mountPath: /envconsul/
        - name: envconsul-config
          mountPath: /envconsul/config/config.hcl
          subPath: config.hcl
      volumes:
      - name: envconsul-share
        emptyDir:
          medium: Memory
      - name: envconsul-config
        configMap:
          name: envconsul
